import os
import pandas as pd
from dotenv import load_dotenv
import google.generativeai as genai
import logging

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

def generate_company_summary(ticker_symbol: str) -> str:
    """
    Generates a detailed financial summary for a given company by reading from the
    combined analysis report, powered by the Gemini API.
    Returns the generated text (or an error string).
    """
    # 1. Load env and configure API
    load_dotenv()
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        logger.error("GEMINI_API_KEY not found in .env file.")
        return "Error: GEMINI_API_KEY not found. Please check your .env file."

    genai.configure(api_key=api_key)
    model = genai.GenerativeModel('gemini-1.5-flash')
    generation_config = genai.types.GenerationConfig(max_output_tokens=2048)

    # 2. Load the SINGLE combined analysis report CSV
    try:
        report_path = 'combined_financial_analysis_report.csv'
        logger.info(f"Loading combined analysis report from: {report_path}")
        combined_df = pd.read_csv(report_path)
    except FileNotFoundError:
        error_msg = f"Error: The file '{report_path}' was not found. Please run the main analysis script first."
        logger.error(error_msg)
        return error_msg

    # 3. Gather all required data from the single row for the company
    company_data = combined_df[combined_df['Ticker Symbol'] == ticker_symbol]
    
    if company_data.empty:
        error_msg = f"Error: No data found for ticker '{ticker_symbol}' in the report."
        logger.error(error_msg)
        return error_msg
        
    company_row = company_data.iloc[0]

    anomaly_info = f"Detected {int(company_row['Number of Anomalies'])} anomaly/anomalies in recent years."

    last_historical_year_data = {
        'Total Revenue': company_row['Total Revenue Y4'],
        'Net Income': company_row['Net Income Y4'],
        'Earnings Per Share': company_row['Earnings Per Share Y4']
    }
    
    forecast_data = {
        'Predicted Total Revenue': company_row['Predicted Total Revenue'],
        'Predicted Net Income': company_row['Predicted Net Income'],
        'Predicted Total Assets': company_row['Predicted Total Assets'],
        'Predicted Earnings Per Share': company_row['Predicted Earnings Per Share']
    }
    
    # --- THIS IS THE EDITED PROMPT ---
    prompt = f"""
    Act as a senior financial analyst providing a detailed report on {ticker_symbol}.

    Context:
    You have been provided with data generated by a proprietary machine learning system. Your task is to synthesize this information into a comprehensive, human-readable report. The report must be detailed and provide actionable suggestions for different audiences.

    Machine Learning Model Outputs:
    - Anomaly Detection: {anomaly_info}
    - Last Available Historical Year Data:
      - Total Revenue: ${last_historical_year_data['Total Revenue']/1e9:.2f} Billion
      - Net Income: ${last_historical_year_data['Net Income']/1e9:.2f} Billion
      - Earnings Per Share (EPS): ${last_historical_year_data['Earnings Per Share']:.2f}
    - Financial Forecast for the Next Year:
      - Predicted Total Revenue: ${forecast_data['Predicted Total Revenue']/1e9:.2f} Billion
      - Predicted Net Income: ${forecast_data['Predicted Net Income']/1e9:.2f} Billion
      - Predicted Total Assets: ${forecast_data['Predicted Total Assets']/1e9:.2f} Billion
      - Predicted Earnings Per Share (EPS): ${forecast_data['Predicted Earnings Per Share']:.2f}

    Your Task:
    Generate a report with the following structure:

    **1. Executive Summary:**
       - Start with a brief, high-level overview of the company's situation based on the data.
       - Mention the anomaly findings (or lack thereof) and the general direction of the forecast (growth, decline, stability).

    **2. Detailed Analysis:**
       - **Historical Context & Anomalies:** Elaborate on the anomaly finding. If an anomaly was detected, explain what this might imply (e.g., a one-time event, a significant shift in strategy). If no anomalies were found, state that the company has shown stable and predictable performance.
       - **Future Outlook (Forecast Analysis):** Analyze the forecast in detail. Compare the predicted revenue, net income, and EPS to the most recent historical year. Is the company predicted to grow? Is profitability expected to increase or decrease?

    **3. Suggestions for Stakeholders:**
       - **For Investors/Shareholders:** Provide clear, actionable **suggestions and recommendations**. Recommend whether they should be optimistic due to growth, or cautious due to anomalies. Suggest specific areas of the business to monitor (like profit margins or asset efficiency). **Frame these as direct recommendations, NOT a list of questions.**
       - **For Financial Analysts:** What specific areas of the company's financials require a deeper dive? Does the lack of anomalies suggest that standard valuation models are likely to be reliable? Are the forecast numbers realistic, and what macroeconomic factors could influence them?

    **Format the entire response using clear headings. Use **bold text** for headings and to emphasize key financial terms or conclusions.**
    """
    # --- END OF EDITED PROMPT ---

    try:
        logger.info(f"Sending prompt to Gemini API for {ticker_symbol}...")
        response = model.generate_content(prompt, generation_config=generation_config)
        
        logger.info(f"Successfully generated summary for {ticker_symbol}.")
        return response.text

    except Exception as e:
        logger.error(f"GEMINI API ERROR for {ticker_symbol}: {e}")
        return f"An error occurred while generating the report: {e}"

# Example Usage
if __name__ == '__main__':
    ticker_to_test = 'AAL' # Replace with any ticker from your report
    summary = generate_company_summary(ticker_to_test)
    
    print(f"\n--- AI-Generated Financial Report for: {ticker_to_test} ---")
    print(summary)
    print("--- End of Report ---\n")